open_test: open_test.c call.h call.c inode.h inode.c
	gcc -o open_test open_test.c call.h call.c inode.h inode.c && \
	gcc -o read_test read_test.c call.h call.c inode.h inode.c

clean:
	rm open_test read_test