all: 
	gcc -o example1 example1.c
	gcc -o example2 example2.c
	gcc -o example3 example3.c
	gcc -o example4 example4.c

example1: example1.c
	gcc -o example1 example1.c

example2: example2.c
	gcc -o example2 example2.c

example3: example3.c
	gcc -o example3 example3.c

example4: example4.c
	gcc -o example4 example4.c

clean:
	rm example1
	rm example2
	rm example3
	rm example4
